### ISSUE TITLE
File permissions are broken

### ISSUE THREAD

**Issue by flying-sheep** [jonschlinkert/array-unique#5]
when I try to import this, i get a permission error. The files in the tarball from the NPM registry all have the permissions `700`, but should have `644`.

**Comment by jonschlinkert** [comment]
Did you try deleting everything in node_modules and reinstalling?

**Comment by flying-sheep** [comment]
no need, the error is definitely in the (0.2.1) package. could you please publish a 0.2.2 that is simply 0.2.1 with fixed file permissions? apparently i have a package depending on `array-unique: ^0.2`

```console
$ curl -s https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz | lz
Reading directory of  standard input.
-rwx------ 501/20          862 2015-03-25 04:46 package/package.json
-rwx------ 501/20         1965 2015-03-25 04:46 package/README.md
-rwx------ 501/20         1088 2015-03-25 04:46 package/LICENSE
-rwx------ 501/20          512 2015-03-25 04:46 package/index.js
```

0.3.2 doesn’t have the problem:

```console
$ curl -s https://registry.npmjs.org/array-unique/-/array-unique-0.3.2.tgz | lz
Reading directory of  standard input.
-rw-r--r-- 503/20         1224 2016-08-01 02:54 package/package.json
-rwx------ 503/20         4021 2016-08-01 02:51 package/README.md
-rwx------ 503/20         1087 2015-03-25 04:46 package/LICENSE
-rw-r--r-- 503/20          829 2016-08-01 02:48 package/index.js
```

still weird permissions though, why aren’t they all `644`? only executables should be +x, and there’s no reason to make non security related files unreadable for other people than the user

**Comment by jonschlinkert** [comment]
> Did you try deleting everything in node_modules and reinstalling?

**Comment by flying-sheep** [comment]
1. yarn creates predictably always the same dep tree
2. i just proved that the permissions in the tarball are borked

when i do what you say, yarn will just use the cached tarball, extract it, and the exact same files with the exact same permissions will be created in the exactly same locations.

so no, i didn’t do it because i *know* it won’t help. not assume: know. 😉

**Comment by jonschlinkert** [comment]
> i just proved that the permissions in the tarball are borked

Yes, you proved that the tarball you have on your box has the wrong permissions. You didn't prove anything else. NPM creates the tarball, I've had this happen many times. It almost always works when you delete and reinstall. 

> when i do what you say, yarn will just use the cached tarball, extract it

then do `yarn upgrade` or clear the cache and do reinstall.

**Comment by flying-sheep** [comment]
> Yes, you proved that the tarball you have on your box has the wrong permissions. You didn't prove anything else.

wrong, please check out the actual code i posted:

> ```console
> $ curl -s https://registry.npmjs.org/array-unique/-/array-unique-0.2.1.tgz | lz
> Reading directory of  standard input.
> -rwx------ 501/20          862 2015-03-25 04:46 package/package.json
> -rwx------ 501/20         1965 2015-03-25 04:46 package/README.md
> -rwx------ 501/20         1088 2015-03-25 04:46 package/LICENSE
> -rwx------ 501/20          512 2015-03-25 04:46 package/index.js
> ```

this shows that the permissions on the npm registry are broken, not locally.

**Comment by flying-sheep** [comment]
but fine…

```console
$ # not cleaning cache since beyond doubt the npm version is broken
$ yarn --production  # micromatch is a direct depencency
$ ls -l node_modules/array-unique
insgesamt 16
-rwx------ 1 me me  512 25. Mär 2015  index.js
-rwx------ 1 me me 1088 25. Mär 2015  LICENSE
-rwx------ 1 me me  862 25. Mär 2015  package.json
-rwx------ 1 me me 1965 25. Mär 2015  README.md
```

i was right.

**Comment by jonschlinkert** [comment]
but fine what? you still didn't do what I said. 

Are you suggesting that all 110 million downloads since the last release have had a permissions issue? And if so, what are you doing or not doing that differs from every other user?

**Comment by doowb** [comment]
@flying-sheep I think this might be a different issue because I have different permissions on my machine:

```
~/work/doowb/recipes ± ls -l node_modules/array-unique
total 32
-rwxr--r--  1 doowb  staff  1088 Mar 24  2015 LICENSE
-rwxr--r--  1 doowb  staff  1965 Mar 24  2015 README.md
-rwxr--r--  1 doowb  staff   512 Mar 24  2015 index.js
-rwxr--r--  1 doowb  staff  2549 May  6 19:46 package.json
```

I'm on OSX and used npm to install.

**Comment by jonschlinkert** [comment]
and I get

```sh
➜  array-unique ls -l
total 40
-rwxr--r--  1 jonschlinkert  admin  1087 Mar 24  2015 LICENSE
-rwxr--r--  1 jonschlinkert  admin  4021 Jul 31  2016 README.md
-rw-r--r--  1 jonschlinkert  admin   829 Jul 31  2016 index.js
-rw-r--r--  1 jonschlinkert  admin  7192 May 23 09:51 package.json
```

The main point is that you're not doing what I asked you to do - and I suggested something that in my own personal experience has worked in the past. 

Start by reviewing all of the permissions-related issues on yarn and npm before filing issues on individual modules:

- https://github.com/yarnpkg/yarn/search?q=file+permissions&type=Issues&utf8=%E2%9C%93
- https://github.com/npm/npm/search?q=file+permissions&type=Issues&utf8=%E2%9C%93

**Comment by flying-sheep** [comment]
haha your skepticism is really refreshing. as a maintainer, i can completely feel you, but please: for me you can just assume i know my shit

> And if so, what are you doing or not doing that differs from every other user?

system-wide install 😉

on arch linux, there are packages for quite some node-based CLI packages. that works by creating a package with the whole tree created by `npm install -g --prefix ...` + metadata, and installing that… for root:root.

for such installs, you want binaries/directories to have 755 and the rest 644, so users can read the files, but not modify them.

your permissions (700) mean that a user-wide install works, but only root is allowed to read the array-unique 0.2.1 files.

**Comment by flying-sheep** [comment]
> The main point is that you're not doing what I asked you to do

oh, but i did, even if i knew that it wouldn’t do anything. the “but fine…” just meant that i knew it would be futile, not that i didn’t do it.

**Comment by jonschlinkert** [comment]
> i can completely feel you, but please: for me you can just assume i know my shit

Interesting. I think this sentiment goes both ways. 

One problem I'm aware of is that yarn does not normalize permissions like NPM does. There are many, many issues on both npm and yarn about this and related topics, though, so it's hard to know which one is really the issue.  Also, you're assuming that when I republish this package that the permissions will be different than they are currently. You sure about that? Because it's not guaranteed.  Let's say it yields the same result. What's the next step? Would you then want me to change the permissions on my box so that when yarn preserves the permissions you get what you expect on your system?

**Comment by flying-sheep** [comment]
> I'm on OSX and used npm to install.

so i encountered this bug when taking over an arch linux package from a previous maintainer.

the [initially imported version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gulp-cli&id=0f05779a076f0c5e4d351c0a95feab3a57591de5) had to contain a line commented as `fix permissions`, so at least that other maintainer encountered a permission bug as well

**Comment by flying-sheep** [comment]
> Interesting. I think this sentiment goes both ways.

well, i assume you are experienced. one of those experiences is that users are generally stupid and weird problems like this are usually fixed should when you follow some best practices (turn off and on again, empty cache, …)

in this case however, i *showed* you through pasted console sessions that the permissions in the NPM registry are broken, and told you i’m sure i don’t need to do that (which proved to be correct)

instead of giving me the benefit of doubt when i said that, and actually reading the code block to see what i did, you *assumed* i had done something else than what i showed (you said “Yes, you proved that the tarball you have on your box has the wrong permissions”).

you let your assumptions about your usual bug reporters cloud your judgment. so you assumed it was a local problem on my side even though my evidence in this thread would have showed you that it wasn’t if you had looked.

that’s OK, but please give me the benefit of doubt in the future, OK? 😜

> One problem I'm aware of is that yarn does not normalize permissions like NPM does

according to https://github.com/yarnpkg/yarn/issues/961#issuecomment-292541763 and https://github.com/yarnpkg/yarn/issues/1143#issuecomment-301034020 it does since 0.23. i have yarn 0.24.5. so they probably just didn’t fix it properly.

but still: relying on permission normalization doesn’t mean broken permissions aren’t a bug in the package as well. i’m not sure, but i assume there is no spec that says that a node packaging tool has to normalize permissions in that way.

> Also, you're assuming that when I republish this package that the permissions will be different than they are currently.

1. newer versions of your package have correct permissions
2. you can split the publish part in two and check the permissions in-between:

    ```console
    $ npm pack
    $ tar -tvzf array-unique-0.2.2.tgz  # don’t need lz, tar -tv works
    $ # only proceed if the permissions are correct
    $ npm publish array-unique-0.2.2.tgz
    ```

sounds good? 😄

**Comment by flying-sheep** [comment]
to sum up:

- the array-unique 0.2.1 tarball on NPM has broken permissions
- that specific kind of broken permissions is only a problem when you do a system-wide install
- npm normalizes permissions, yarn doesn’t completely
- releasing array-unique 0.2.2 with correct permissions is both reliably possible (you can check before publishing) and will fix the issue in the rare cases it manifests

so could you please do that? if you want i can bundle a tar file with the correct permissions for you and send it your way (you can then check that i changed nothing but version and permissions via dir-diff)

**Comment by xjamundx** [comment]
FWIW I'm seeing a similar issue with `npm5`. Whereas other modules seem to get permissions like `-rw-rwxr--` this module appears to get installed with `-rwx-wx---`.

If there's anything I can try on my end to work around this that would be great. Our stage environment has different users installing and running things for whatever reason, so I'm getting errors when I try to start my application as soon as I started testing with `npm5`

Also this is probably just a bug with `npm5` and if it is I'm fine with that as well!

**Comment by jonschlinkert** [comment]
closing since you created issues on npm and it should be resolved there.

**Comment by xjamundx** [comment]
Thanks @jonschlinkert

**Comment by eddiemonge** [comment]
Why do the files in this need execute permission? That seems like a vulnerability just waiting to happen
